export {
  TableInsertButton,
  TableInsertHTMLButton,
  TableAddRowAfterButton,
  TableAddRowBeforeButton,
  TableAddColumnAfterButton,
  TableAddColumnBeforeButton,
  TableDeleteRowButton,
  TableDeleteColumnButton,
  TableToggleHeaderRowButton,
  TableToggleHeaderColumnButton,
  TableToggleHeaderCellButton,
  TableMergeCellsButton,
  TableSplitCellButton,
  TableMergeOrSplitButton,
  TableSetCellBackgroundButton,
  TableFixTablesButton,
  TableGoToNextCellButton,
  TableGoToPreviousCellButton,
  TableDeleteButton,
  type TableButtonProps,
} from "./table-button";